### ISSUE TITLE
[feat]: Add the website builder screen

### ISSUE THREAD

**Issue by amezng** [torqbit/torqbit#455]
- [ ] For brand section, use the below properties.

   ```
    logo: /icon/torqbit.png
    description: Master the art of product building and turn your ideas into
      successful, scalable products
    ogImage: /icon/torqbit.png
    favicon: /favicon.ico
    socialLinks:
      discord: https://discord.gg/NserMXcx
      github: https://github.com/torqbit
      youtube: https://www.youtube.com/@torqbit
    name: Peace School
    brandColor: "#86d78c"
    title: Spreads peace and harmony

    ``` 
- [ ] Create side nav with sections - brand, hero-section, feature-section
